//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_PRODLIB_CLPFNDG
    {
        public int ACCTNO { get; set; }
        public string CLCOWN { get; set; }
        public Nullable<int> GLPLAN { get; set; }
        public Nullable<int> LSCOD1 { get; set; }
        public Nullable<decimal> MINNBR { get; set; }
        public Nullable<int> SBSCOD { get; set; }
    }
}
