//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_SUB_OWNER
    {
        public int OWNER_ID { get; set; }
        public string OWNER { get; set; }
        public string SUB_REQUIREMENTS { get; set; }
    }
}
