//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DocumentContext : DbContext
    {
        public DocumentContext()
            : base("name=DocumentContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DOCUS_ASM_ASSIGNEE> DOCUS_ASM_ASSIGNEE { get; set; }
        public DbSet<DOCUS_ASM_ASSIGNMENTS> DOCUS_ASM_ASSIGNMENTS { get; set; }
        public DbSet<DOCUS_PRODLIB_CLPACMST> DOCUS_PRODLIB_CLPACMST { get; set; }
        public DbSet<DOCUS_PRODLIB_CLPCLMST> DOCUS_PRODLIB_CLPCLMST { get; set; }
        public DbSet<DOCUS_PRODLIB_CLPCUSTD> DOCUS_PRODLIB_CLPCUSTD { get; set; }
        public DbSet<DOCUS_PRODLIB_CLPFNDG> DOCUS_PRODLIB_CLPFNDG { get; set; }
        public DbSet<DOCUS_PRODLIB_CLPHDOC> DOCUS_PRODLIB_CLPHDOC { get; set; }
        public DbSet<DOCUS_SUB_REQUEST> DOCUS_SUB_REQUEST { get; set; }
        public DbSet<DOCUS_SYS_CUSTODIAN> DOCUS_SYS_CUSTODIAN { get; set; }
        public DbSet<DOCUS_SYS_LOOKUP> DOCUS_SYS_LOOKUP { get; set; }
        public DbSet<FEE> FEEs { get; set; }
        public DbSet<LOANTYPE> LOANTYPEs { get; set; }
        public DbSet<OWNER> OWNERs { get; set; }
        public DbSet<REPRESENTATIVE> REPRESENTATIVEs { get; set; }
        public DbSet<REQUESTTYPE> REQUESTTYPEs { get; set; }
        public DbSet<STATUS> STATUS { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_ASSIGNED_TO> DOCUS_ASM_LOOKUP_ASSIGNED_TO { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_ASSIGNOR_DONOTUSE> DOCUS_ASM_LOOKUP_ASSIGNOR_DONOTUSE { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_DATA_ENTRY_BY> DOCUS_ASM_LOOKUP_DATA_ENTRY_BY { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_DOC_TYPE> DOCUS_ASM_LOOKUP_DOC_TYPE { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_ENTERED_BY> DOCUS_ASM_LOOKUP_ENTERED_BY { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_PREPARED_BY> DOCUS_ASM_LOOKUP_PREPARED_BY { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_PROCESSED_BY> DOCUS_ASM_LOOKUP_PROCESSED_BY { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_PROCESSOR_NAME> DOCUS_ASM_LOOKUP_PROCESSOR_NAME { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_RECORDING_STATUS> DOCUS_ASM_LOOKUP_RECORDING_STATUS { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_REQUEST_REASON> DOCUS_ASM_LOOKUP_REQUEST_REASON { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_REQUEST_TYPE> DOCUS_ASM_LOOKUP_REQUEST_TYPE { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_REQUESTOR_NAME> DOCUS_ASM_LOOKUP_REQUESTOR_NAME { get; set; }
        public DbSet<DOCUS_ASM_LOOKUP_STATUS> DOCUS_ASM_LOOKUP_STATUS { get; set; }
        public DbSet<DOCUS_SUB_LOOKUP_FEE> DOCUS_SUB_LOOKUP_FEE { get; set; }
        public DbSet<DOCUS_SUB_LOOKUP_LOAN_TYPE> DOCUS_SUB_LOOKUP_LOAN_TYPE { get; set; }
        public DbSet<DOCUS_SUB_LOOKUP_REPRESENTATIVE> DOCUS_SUB_LOOKUP_REPRESENTATIVE { get; set; }
        public DbSet<DOCUS_SUB_LOOKUP_REQUEST_TYPE> DOCUS_SUB_LOOKUP_REQUEST_TYPE { get; set; }
        public DbSet<DOCUS_SUB_LOOKUP_STATUS> DOCUS_SUB_LOOKUP_STATUS { get; set; }
        public DbSet<DOCUS_SUB_OWNER> DOCUS_SUB_OWNER { get; set; }
        public DbSet<DOCUS_ASM_ASSIGNMENT_NOTES> DOCUS_ASM_ASSIGNMENT_NOTES { get; set; }
    
        public virtual ObjectResult<DOCUS_ASM_GET_GTA_FIELDS_Result> DOCUS_ASM_GET_GTA_FIELDS(Nullable<int> aCCOUNT_NUMBER)
        {
            var aCCOUNT_NUMBERParameter = aCCOUNT_NUMBER.HasValue ?
                new ObjectParameter("ACCOUNT_NUMBER", aCCOUNT_NUMBER) :
                new ObjectParameter("ACCOUNT_NUMBER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DOCUS_ASM_GET_GTA_FIELDS_Result>("DOCUS_ASM_GET_GTA_FIELDS", aCCOUNT_NUMBERParameter);
        }
    
        public virtual int DOCUS_ASM_INSERT_ASSIGNMENT(Nullable<int> aCCOUNT_NUMBER, string bORROWER_LAST_NAME, Nullable<int> rEQUEST_TYPE_ID, Nullable<int> rEQUEST_REASON_ID, Nullable<int> dOC_TYPE_ID, Nullable<System.DateTime> rEQUEST_DATE, Nullable<System.DateTime> dATE_ENTERED, Nullable<int> rEQUEST_ENTERED_BY_ID, Nullable<int> rEQUESTOR_NAME_ID, Nullable<bool> mERS_INDICATOR, Nullable<bool> mERS_UPDATED, string aSSIGNOR, string aSSIGNEE, Nullable<int> aSSIGNED_TO_ID, Nullable<int> pROCESSED_BY_ID, Nullable<System.DateTime> aSSIGNED_DATE, Nullable<System.DateTime> cOLLATERAL_FILE_REQUEST_DATE, Nullable<bool> aOM_IN_COL, string tHIRD_PARTY_CONTACT_NAME, string tHIRD_PARTY_CONTACT_INFO, Nullable<int> sTATUS_ID, string tRACKING_NUMBER, Nullable<System.DateTime> lAST_STATUS_DATE, Nullable<System.DateTime> fOLLOW_UP_DATE, Nullable<System.DateTime> sALE_DATE, Nullable<System.DateTime> dATE_COMPLETE, string cOMPANY_NAME, string cOMPANY_ADDRESS, string aTTENTION_TO, string cITY, string sTATE, string zIP, Nullable<bool> rUSH, Nullable<int> cUSTODIAN_ID, string cUST_REF_NUMBER, string mERS_INFO_NUMBER, Nullable<int> lSCOD1, Nullable<int> sBSCOD, Nullable<int> rECORDED_STATUS_ID, string rECORDED_COUNTY, Nullable<System.DateTime> rECORDED_DATE, string rECORDED_DOC_INST_NUM, string rECORDED_BOOK, string rECORDED_PAGE)
        {
            var aCCOUNT_NUMBERParameter = aCCOUNT_NUMBER.HasValue ?
                new ObjectParameter("ACCOUNT_NUMBER", aCCOUNT_NUMBER) :
                new ObjectParameter("ACCOUNT_NUMBER", typeof(int));
    
            var bORROWER_LAST_NAMEParameter = bORROWER_LAST_NAME != null ?
                new ObjectParameter("BORROWER_LAST_NAME", bORROWER_LAST_NAME) :
                new ObjectParameter("BORROWER_LAST_NAME", typeof(string));
    
            var rEQUEST_TYPE_IDParameter = rEQUEST_TYPE_ID.HasValue ?
                new ObjectParameter("REQUEST_TYPE_ID", rEQUEST_TYPE_ID) :
                new ObjectParameter("REQUEST_TYPE_ID", typeof(int));
    
            var rEQUEST_REASON_IDParameter = rEQUEST_REASON_ID.HasValue ?
                new ObjectParameter("REQUEST_REASON_ID", rEQUEST_REASON_ID) :
                new ObjectParameter("REQUEST_REASON_ID", typeof(int));
    
            var dOC_TYPE_IDParameter = dOC_TYPE_ID.HasValue ?
                new ObjectParameter("DOC_TYPE_ID", dOC_TYPE_ID) :
                new ObjectParameter("DOC_TYPE_ID", typeof(int));
    
            var rEQUEST_DATEParameter = rEQUEST_DATE.HasValue ?
                new ObjectParameter("REQUEST_DATE", rEQUEST_DATE) :
                new ObjectParameter("REQUEST_DATE", typeof(System.DateTime));
    
            var dATE_ENTEREDParameter = dATE_ENTERED.HasValue ?
                new ObjectParameter("DATE_ENTERED", dATE_ENTERED) :
                new ObjectParameter("DATE_ENTERED", typeof(System.DateTime));
    
            var rEQUEST_ENTERED_BY_IDParameter = rEQUEST_ENTERED_BY_ID.HasValue ?
                new ObjectParameter("REQUEST_ENTERED_BY_ID", rEQUEST_ENTERED_BY_ID) :
                new ObjectParameter("REQUEST_ENTERED_BY_ID", typeof(int));
    
            var rEQUESTOR_NAME_IDParameter = rEQUESTOR_NAME_ID.HasValue ?
                new ObjectParameter("REQUESTOR_NAME_ID", rEQUESTOR_NAME_ID) :
                new ObjectParameter("REQUESTOR_NAME_ID", typeof(int));
    
            var mERS_INDICATORParameter = mERS_INDICATOR.HasValue ?
                new ObjectParameter("MERS_INDICATOR", mERS_INDICATOR) :
                new ObjectParameter("MERS_INDICATOR", typeof(bool));
    
            var mERS_UPDATEDParameter = mERS_UPDATED.HasValue ?
                new ObjectParameter("MERS_UPDATED", mERS_UPDATED) :
                new ObjectParameter("MERS_UPDATED", typeof(bool));
    
            var aSSIGNORParameter = aSSIGNOR != null ?
                new ObjectParameter("ASSIGNOR", aSSIGNOR) :
                new ObjectParameter("ASSIGNOR", typeof(string));
    
            var aSSIGNEEParameter = aSSIGNEE != null ?
                new ObjectParameter("ASSIGNEE", aSSIGNEE) :
                new ObjectParameter("ASSIGNEE", typeof(string));
    
            var aSSIGNED_TO_IDParameter = aSSIGNED_TO_ID.HasValue ?
                new ObjectParameter("ASSIGNED_TO_ID", aSSIGNED_TO_ID) :
                new ObjectParameter("ASSIGNED_TO_ID", typeof(int));
    
            var pROCESSED_BY_IDParameter = pROCESSED_BY_ID.HasValue ?
                new ObjectParameter("PROCESSED_BY_ID", pROCESSED_BY_ID) :
                new ObjectParameter("PROCESSED_BY_ID", typeof(int));
    
            var aSSIGNED_DATEParameter = aSSIGNED_DATE.HasValue ?
                new ObjectParameter("ASSIGNED_DATE", aSSIGNED_DATE) :
                new ObjectParameter("ASSIGNED_DATE", typeof(System.DateTime));
    
            var cOLLATERAL_FILE_REQUEST_DATEParameter = cOLLATERAL_FILE_REQUEST_DATE.HasValue ?
                new ObjectParameter("COLLATERAL_FILE_REQUEST_DATE", cOLLATERAL_FILE_REQUEST_DATE) :
                new ObjectParameter("COLLATERAL_FILE_REQUEST_DATE", typeof(System.DateTime));
    
            var aOM_IN_COLParameter = aOM_IN_COL.HasValue ?
                new ObjectParameter("AOM_IN_COL", aOM_IN_COL) :
                new ObjectParameter("AOM_IN_COL", typeof(bool));
    
            var tHIRD_PARTY_CONTACT_NAMEParameter = tHIRD_PARTY_CONTACT_NAME != null ?
                new ObjectParameter("THIRD_PARTY_CONTACT_NAME", tHIRD_PARTY_CONTACT_NAME) :
                new ObjectParameter("THIRD_PARTY_CONTACT_NAME", typeof(string));
    
            var tHIRD_PARTY_CONTACT_INFOParameter = tHIRD_PARTY_CONTACT_INFO != null ?
                new ObjectParameter("THIRD_PARTY_CONTACT_INFO", tHIRD_PARTY_CONTACT_INFO) :
                new ObjectParameter("THIRD_PARTY_CONTACT_INFO", typeof(string));
    
            var sTATUS_IDParameter = sTATUS_ID.HasValue ?
                new ObjectParameter("STATUS_ID", sTATUS_ID) :
                new ObjectParameter("STATUS_ID", typeof(int));
    
            var tRACKING_NUMBERParameter = tRACKING_NUMBER != null ?
                new ObjectParameter("TRACKING_NUMBER", tRACKING_NUMBER) :
                new ObjectParameter("TRACKING_NUMBER", typeof(string));
    
            var lAST_STATUS_DATEParameter = lAST_STATUS_DATE.HasValue ?
                new ObjectParameter("LAST_STATUS_DATE", lAST_STATUS_DATE) :
                new ObjectParameter("LAST_STATUS_DATE", typeof(System.DateTime));
    
            var fOLLOW_UP_DATEParameter = fOLLOW_UP_DATE.HasValue ?
                new ObjectParameter("FOLLOW_UP_DATE", fOLLOW_UP_DATE) :
                new ObjectParameter("FOLLOW_UP_DATE", typeof(System.DateTime));
    
            var sALE_DATEParameter = sALE_DATE.HasValue ?
                new ObjectParameter("SALE_DATE", sALE_DATE) :
                new ObjectParameter("SALE_DATE", typeof(System.DateTime));
    
            var dATE_COMPLETEParameter = dATE_COMPLETE.HasValue ?
                new ObjectParameter("DATE_COMPLETE", dATE_COMPLETE) :
                new ObjectParameter("DATE_COMPLETE", typeof(System.DateTime));
    
            var cOMPANY_NAMEParameter = cOMPANY_NAME != null ?
                new ObjectParameter("COMPANY_NAME", cOMPANY_NAME) :
                new ObjectParameter("COMPANY_NAME", typeof(string));
    
            var cOMPANY_ADDRESSParameter = cOMPANY_ADDRESS != null ?
                new ObjectParameter("COMPANY_ADDRESS", cOMPANY_ADDRESS) :
                new ObjectParameter("COMPANY_ADDRESS", typeof(string));
    
            var aTTENTION_TOParameter = aTTENTION_TO != null ?
                new ObjectParameter("ATTENTION_TO", aTTENTION_TO) :
                new ObjectParameter("ATTENTION_TO", typeof(string));
    
            var cITYParameter = cITY != null ?
                new ObjectParameter("CITY", cITY) :
                new ObjectParameter("CITY", typeof(string));
    
            var sTATEParameter = sTATE != null ?
                new ObjectParameter("STATE", sTATE) :
                new ObjectParameter("STATE", typeof(string));
    
            var zIPParameter = zIP != null ?
                new ObjectParameter("ZIP", zIP) :
                new ObjectParameter("ZIP", typeof(string));
    
            var rUSHParameter = rUSH.HasValue ?
                new ObjectParameter("RUSH", rUSH) :
                new ObjectParameter("RUSH", typeof(bool));
    
            var cUSTODIAN_IDParameter = cUSTODIAN_ID.HasValue ?
                new ObjectParameter("CUSTODIAN_ID", cUSTODIAN_ID) :
                new ObjectParameter("CUSTODIAN_ID", typeof(int));
    
            var cUST_REF_NUMBERParameter = cUST_REF_NUMBER != null ?
                new ObjectParameter("CUST_REF_NUMBER", cUST_REF_NUMBER) :
                new ObjectParameter("CUST_REF_NUMBER", typeof(string));
    
            var mERS_INFO_NUMBERParameter = mERS_INFO_NUMBER != null ?
                new ObjectParameter("MERS_INFO_NUMBER", mERS_INFO_NUMBER) :
                new ObjectParameter("MERS_INFO_NUMBER", typeof(string));
    
            var lSCOD1Parameter = lSCOD1.HasValue ?
                new ObjectParameter("LSCOD1", lSCOD1) :
                new ObjectParameter("LSCOD1", typeof(int));
    
            var sBSCODParameter = sBSCOD.HasValue ?
                new ObjectParameter("SBSCOD", sBSCOD) :
                new ObjectParameter("SBSCOD", typeof(int));
    
            var rECORDED_STATUS_IDParameter = rECORDED_STATUS_ID.HasValue ?
                new ObjectParameter("RECORDED_STATUS_ID", rECORDED_STATUS_ID) :
                new ObjectParameter("RECORDED_STATUS_ID", typeof(int));
    
            var rECORDED_COUNTYParameter = rECORDED_COUNTY != null ?
                new ObjectParameter("RECORDED_COUNTY", rECORDED_COUNTY) :
                new ObjectParameter("RECORDED_COUNTY", typeof(string));
    
            var rECORDED_DATEParameter = rECORDED_DATE.HasValue ?
                new ObjectParameter("RECORDED_DATE", rECORDED_DATE) :
                new ObjectParameter("RECORDED_DATE", typeof(System.DateTime));
    
            var rECORDED_DOC_INST_NUMParameter = rECORDED_DOC_INST_NUM != null ?
                new ObjectParameter("RECORDED_DOC_INST_NUM", rECORDED_DOC_INST_NUM) :
                new ObjectParameter("RECORDED_DOC_INST_NUM", typeof(string));
    
            var rECORDED_BOOKParameter = rECORDED_BOOK != null ?
                new ObjectParameter("RECORDED_BOOK", rECORDED_BOOK) :
                new ObjectParameter("RECORDED_BOOK", typeof(string));
    
            var rECORDED_PAGEParameter = rECORDED_PAGE != null ?
                new ObjectParameter("RECORDED_PAGE", rECORDED_PAGE) :
                new ObjectParameter("RECORDED_PAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DOCUS_ASM_INSERT_ASSIGNMENT", aCCOUNT_NUMBERParameter, bORROWER_LAST_NAMEParameter, rEQUEST_TYPE_IDParameter, rEQUEST_REASON_IDParameter, dOC_TYPE_IDParameter, rEQUEST_DATEParameter, dATE_ENTEREDParameter, rEQUEST_ENTERED_BY_IDParameter, rEQUESTOR_NAME_IDParameter, mERS_INDICATORParameter, mERS_UPDATEDParameter, aSSIGNORParameter, aSSIGNEEParameter, aSSIGNED_TO_IDParameter, pROCESSED_BY_IDParameter, aSSIGNED_DATEParameter, cOLLATERAL_FILE_REQUEST_DATEParameter, aOM_IN_COLParameter, tHIRD_PARTY_CONTACT_NAMEParameter, tHIRD_PARTY_CONTACT_INFOParameter, sTATUS_IDParameter, tRACKING_NUMBERParameter, lAST_STATUS_DATEParameter, fOLLOW_UP_DATEParameter, sALE_DATEParameter, dATE_COMPLETEParameter, cOMPANY_NAMEParameter, cOMPANY_ADDRESSParameter, aTTENTION_TOParameter, cITYParameter, sTATEParameter, zIPParameter, rUSHParameter, cUSTODIAN_IDParameter, cUST_REF_NUMBERParameter, mERS_INFO_NUMBERParameter, lSCOD1Parameter, sBSCODParameter, rECORDED_STATUS_IDParameter, rECORDED_COUNTYParameter, rECORDED_DATEParameter, rECORDED_DOC_INST_NUMParameter, rECORDED_BOOKParameter, rECORDED_PAGEParameter);
        }
    
        public virtual int DOCUS_ASM_UPDATE_ASSIGNMENT(Nullable<int> aSSIGNMENT_ID, Nullable<int> aCCOUNT_NUMBER, string bORROWER_LAST_NAME, Nullable<int> rEQUEST_TYPE_ID, Nullable<int> rEQUEST_REASON_ID, Nullable<int> dOC_TYPE_ID, Nullable<System.DateTime> rEQUEST_DATE, Nullable<System.DateTime> dATE_ENTERED, Nullable<int> rEQUEST_ENTERED_BY_ID, Nullable<int> rEQUESTOR_NAME_ID, Nullable<bool> mERS_INDICATOR, Nullable<bool> mERS_UPDATED, string aSSIGNOR, string aSSIGNEE, Nullable<int> aSSIGNED_TO_ID, Nullable<int> pROCESSED_BY_ID, Nullable<System.DateTime> aSSIGNED_DATE, Nullable<System.DateTime> cOLLATERAL_FILE_REQUEST_DATE, Nullable<bool> aOM_IN_COL, string tHIRD_PARTY_CONTACT_NAME, string tHIRD_PARTY_CONTACT_INFO, Nullable<int> sTATUS_ID, string tRACKING_NUMBER, Nullable<System.DateTime> lAST_STATUS_DATE, Nullable<System.DateTime> fOLLOW_UP_DATE, Nullable<System.DateTime> sALE_DATE, Nullable<System.DateTime> dATE_COMPLETE, string cOMPANY_NAME, string cOMPANY_ADDRESS, string aTTENTION_TO, string cITY, string sTATE, string zIP, Nullable<bool> rUSH, Nullable<int> cUSTODIAN_ID, string cUST_REF_NUMBER, string mERS_INFO_NUMBER, Nullable<int> lSCOD1, Nullable<int> sBSCOD, Nullable<int> rECORDED_STATUS_ID, string rECORDED_COUNTY, Nullable<System.DateTime> rECORDED_DATE, string rECORDED_DOC_INST_NUM, string rECORDED_BOOK, string rECORDED_PAGE)
        {
            var aSSIGNMENT_IDParameter = aSSIGNMENT_ID.HasValue ?
                new ObjectParameter("ASSIGNMENT_ID", aSSIGNMENT_ID) :
                new ObjectParameter("ASSIGNMENT_ID", typeof(int));
    
            var aCCOUNT_NUMBERParameter = aCCOUNT_NUMBER.HasValue ?
                new ObjectParameter("ACCOUNT_NUMBER", aCCOUNT_NUMBER) :
                new ObjectParameter("ACCOUNT_NUMBER", typeof(int));
    
            var bORROWER_LAST_NAMEParameter = bORROWER_LAST_NAME != null ?
                new ObjectParameter("BORROWER_LAST_NAME", bORROWER_LAST_NAME) :
                new ObjectParameter("BORROWER_LAST_NAME", typeof(string));
    
            var rEQUEST_TYPE_IDParameter = rEQUEST_TYPE_ID.HasValue ?
                new ObjectParameter("REQUEST_TYPE_ID", rEQUEST_TYPE_ID) :
                new ObjectParameter("REQUEST_TYPE_ID", typeof(int));
    
            var rEQUEST_REASON_IDParameter = rEQUEST_REASON_ID.HasValue ?
                new ObjectParameter("REQUEST_REASON_ID", rEQUEST_REASON_ID) :
                new ObjectParameter("REQUEST_REASON_ID", typeof(int));
    
            var dOC_TYPE_IDParameter = dOC_TYPE_ID.HasValue ?
                new ObjectParameter("DOC_TYPE_ID", dOC_TYPE_ID) :
                new ObjectParameter("DOC_TYPE_ID", typeof(int));
    
            var rEQUEST_DATEParameter = rEQUEST_DATE.HasValue ?
                new ObjectParameter("REQUEST_DATE", rEQUEST_DATE) :
                new ObjectParameter("REQUEST_DATE", typeof(System.DateTime));
    
            var dATE_ENTEREDParameter = dATE_ENTERED.HasValue ?
                new ObjectParameter("DATE_ENTERED", dATE_ENTERED) :
                new ObjectParameter("DATE_ENTERED", typeof(System.DateTime));
    
            var rEQUEST_ENTERED_BY_IDParameter = rEQUEST_ENTERED_BY_ID.HasValue ?
                new ObjectParameter("REQUEST_ENTERED_BY_ID", rEQUEST_ENTERED_BY_ID) :
                new ObjectParameter("REQUEST_ENTERED_BY_ID", typeof(int));
    
            var rEQUESTOR_NAME_IDParameter = rEQUESTOR_NAME_ID.HasValue ?
                new ObjectParameter("REQUESTOR_NAME_ID", rEQUESTOR_NAME_ID) :
                new ObjectParameter("REQUESTOR_NAME_ID", typeof(int));
    
            var mERS_INDICATORParameter = mERS_INDICATOR.HasValue ?
                new ObjectParameter("MERS_INDICATOR", mERS_INDICATOR) :
                new ObjectParameter("MERS_INDICATOR", typeof(bool));
    
            var mERS_UPDATEDParameter = mERS_UPDATED.HasValue ?
                new ObjectParameter("MERS_UPDATED", mERS_UPDATED) :
                new ObjectParameter("MERS_UPDATED", typeof(bool));
    
            var aSSIGNORParameter = aSSIGNOR != null ?
                new ObjectParameter("ASSIGNOR", aSSIGNOR) :
                new ObjectParameter("ASSIGNOR", typeof(string));
    
            var aSSIGNEEParameter = aSSIGNEE != null ?
                new ObjectParameter("ASSIGNEE", aSSIGNEE) :
                new ObjectParameter("ASSIGNEE", typeof(string));
    
            var aSSIGNED_TO_IDParameter = aSSIGNED_TO_ID.HasValue ?
                new ObjectParameter("ASSIGNED_TO_ID", aSSIGNED_TO_ID) :
                new ObjectParameter("ASSIGNED_TO_ID", typeof(int));
    
            var pROCESSED_BY_IDParameter = pROCESSED_BY_ID.HasValue ?
                new ObjectParameter("PROCESSED_BY_ID", pROCESSED_BY_ID) :
                new ObjectParameter("PROCESSED_BY_ID", typeof(int));
    
            var aSSIGNED_DATEParameter = aSSIGNED_DATE.HasValue ?
                new ObjectParameter("ASSIGNED_DATE", aSSIGNED_DATE) :
                new ObjectParameter("ASSIGNED_DATE", typeof(System.DateTime));
    
            var cOLLATERAL_FILE_REQUEST_DATEParameter = cOLLATERAL_FILE_REQUEST_DATE.HasValue ?
                new ObjectParameter("COLLATERAL_FILE_REQUEST_DATE", cOLLATERAL_FILE_REQUEST_DATE) :
                new ObjectParameter("COLLATERAL_FILE_REQUEST_DATE", typeof(System.DateTime));
    
            var aOM_IN_COLParameter = aOM_IN_COL.HasValue ?
                new ObjectParameter("AOM_IN_COL", aOM_IN_COL) :
                new ObjectParameter("AOM_IN_COL", typeof(bool));
    
            var tHIRD_PARTY_CONTACT_NAMEParameter = tHIRD_PARTY_CONTACT_NAME != null ?
                new ObjectParameter("THIRD_PARTY_CONTACT_NAME", tHIRD_PARTY_CONTACT_NAME) :
                new ObjectParameter("THIRD_PARTY_CONTACT_NAME", typeof(string));
    
            var tHIRD_PARTY_CONTACT_INFOParameter = tHIRD_PARTY_CONTACT_INFO != null ?
                new ObjectParameter("THIRD_PARTY_CONTACT_INFO", tHIRD_PARTY_CONTACT_INFO) :
                new ObjectParameter("THIRD_PARTY_CONTACT_INFO", typeof(string));
    
            var sTATUS_IDParameter = sTATUS_ID.HasValue ?
                new ObjectParameter("STATUS_ID", sTATUS_ID) :
                new ObjectParameter("STATUS_ID", typeof(int));
    
            var tRACKING_NUMBERParameter = tRACKING_NUMBER != null ?
                new ObjectParameter("TRACKING_NUMBER", tRACKING_NUMBER) :
                new ObjectParameter("TRACKING_NUMBER", typeof(string));
    
            var lAST_STATUS_DATEParameter = lAST_STATUS_DATE.HasValue ?
                new ObjectParameter("LAST_STATUS_DATE", lAST_STATUS_DATE) :
                new ObjectParameter("LAST_STATUS_DATE", typeof(System.DateTime));
    
            var fOLLOW_UP_DATEParameter = fOLLOW_UP_DATE.HasValue ?
                new ObjectParameter("FOLLOW_UP_DATE", fOLLOW_UP_DATE) :
                new ObjectParameter("FOLLOW_UP_DATE", typeof(System.DateTime));
    
            var sALE_DATEParameter = sALE_DATE.HasValue ?
                new ObjectParameter("SALE_DATE", sALE_DATE) :
                new ObjectParameter("SALE_DATE", typeof(System.DateTime));
    
            var dATE_COMPLETEParameter = dATE_COMPLETE.HasValue ?
                new ObjectParameter("DATE_COMPLETE", dATE_COMPLETE) :
                new ObjectParameter("DATE_COMPLETE", typeof(System.DateTime));
    
            var cOMPANY_NAMEParameter = cOMPANY_NAME != null ?
                new ObjectParameter("COMPANY_NAME", cOMPANY_NAME) :
                new ObjectParameter("COMPANY_NAME", typeof(string));
    
            var cOMPANY_ADDRESSParameter = cOMPANY_ADDRESS != null ?
                new ObjectParameter("COMPANY_ADDRESS", cOMPANY_ADDRESS) :
                new ObjectParameter("COMPANY_ADDRESS", typeof(string));
    
            var aTTENTION_TOParameter = aTTENTION_TO != null ?
                new ObjectParameter("ATTENTION_TO", aTTENTION_TO) :
                new ObjectParameter("ATTENTION_TO", typeof(string));
    
            var cITYParameter = cITY != null ?
                new ObjectParameter("CITY", cITY) :
                new ObjectParameter("CITY", typeof(string));
    
            var sTATEParameter = sTATE != null ?
                new ObjectParameter("STATE", sTATE) :
                new ObjectParameter("STATE", typeof(string));
    
            var zIPParameter = zIP != null ?
                new ObjectParameter("ZIP", zIP) :
                new ObjectParameter("ZIP", typeof(string));
    
            var rUSHParameter = rUSH.HasValue ?
                new ObjectParameter("RUSH", rUSH) :
                new ObjectParameter("RUSH", typeof(bool));
    
            var cUSTODIAN_IDParameter = cUSTODIAN_ID.HasValue ?
                new ObjectParameter("CUSTODIAN_ID", cUSTODIAN_ID) :
                new ObjectParameter("CUSTODIAN_ID", typeof(int));
    
            var cUST_REF_NUMBERParameter = cUST_REF_NUMBER != null ?
                new ObjectParameter("CUST_REF_NUMBER", cUST_REF_NUMBER) :
                new ObjectParameter("CUST_REF_NUMBER", typeof(string));
    
            var mERS_INFO_NUMBERParameter = mERS_INFO_NUMBER != null ?
                new ObjectParameter("MERS_INFO_NUMBER", mERS_INFO_NUMBER) :
                new ObjectParameter("MERS_INFO_NUMBER", typeof(string));
    
            var lSCOD1Parameter = lSCOD1.HasValue ?
                new ObjectParameter("LSCOD1", lSCOD1) :
                new ObjectParameter("LSCOD1", typeof(int));
    
            var sBSCODParameter = sBSCOD.HasValue ?
                new ObjectParameter("SBSCOD", sBSCOD) :
                new ObjectParameter("SBSCOD", typeof(int));
    
            var rECORDED_STATUS_IDParameter = rECORDED_STATUS_ID.HasValue ?
                new ObjectParameter("RECORDED_STATUS_ID", rECORDED_STATUS_ID) :
                new ObjectParameter("RECORDED_STATUS_ID", typeof(int));
    
            var rECORDED_COUNTYParameter = rECORDED_COUNTY != null ?
                new ObjectParameter("RECORDED_COUNTY", rECORDED_COUNTY) :
                new ObjectParameter("RECORDED_COUNTY", typeof(string));
    
            var rECORDED_DATEParameter = rECORDED_DATE.HasValue ?
                new ObjectParameter("RECORDED_DATE", rECORDED_DATE) :
                new ObjectParameter("RECORDED_DATE", typeof(System.DateTime));
    
            var rECORDED_DOC_INST_NUMParameter = rECORDED_DOC_INST_NUM != null ?
                new ObjectParameter("RECORDED_DOC_INST_NUM", rECORDED_DOC_INST_NUM) :
                new ObjectParameter("RECORDED_DOC_INST_NUM", typeof(string));
    
            var rECORDED_BOOKParameter = rECORDED_BOOK != null ?
                new ObjectParameter("RECORDED_BOOK", rECORDED_BOOK) :
                new ObjectParameter("RECORDED_BOOK", typeof(string));
    
            var rECORDED_PAGEParameter = rECORDED_PAGE != null ?
                new ObjectParameter("RECORDED_PAGE", rECORDED_PAGE) :
                new ObjectParameter("RECORDED_PAGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DOCUS_ASM_UPDATE_ASSIGNMENT", aSSIGNMENT_IDParameter, aCCOUNT_NUMBERParameter, bORROWER_LAST_NAMEParameter, rEQUEST_TYPE_IDParameter, rEQUEST_REASON_IDParameter, dOC_TYPE_IDParameter, rEQUEST_DATEParameter, dATE_ENTEREDParameter, rEQUEST_ENTERED_BY_IDParameter, rEQUESTOR_NAME_IDParameter, mERS_INDICATORParameter, mERS_UPDATEDParameter, aSSIGNORParameter, aSSIGNEEParameter, aSSIGNED_TO_IDParameter, pROCESSED_BY_IDParameter, aSSIGNED_DATEParameter, cOLLATERAL_FILE_REQUEST_DATEParameter, aOM_IN_COLParameter, tHIRD_PARTY_CONTACT_NAMEParameter, tHIRD_PARTY_CONTACT_INFOParameter, sTATUS_IDParameter, tRACKING_NUMBERParameter, lAST_STATUS_DATEParameter, fOLLOW_UP_DATEParameter, sALE_DATEParameter, dATE_COMPLETEParameter, cOMPANY_NAMEParameter, cOMPANY_ADDRESSParameter, aTTENTION_TOParameter, cITYParameter, sTATEParameter, zIPParameter, rUSHParameter, cUSTODIAN_IDParameter, cUST_REF_NUMBERParameter, mERS_INFO_NUMBERParameter, lSCOD1Parameter, sBSCODParameter, rECORDED_STATUS_IDParameter, rECORDED_COUNTYParameter, rECORDED_DATEParameter, rECORDED_DOC_INST_NUMParameter, rECORDED_BOOKParameter, rECORDED_PAGEParameter);
        }
    
        public virtual int DOCUS_SYS_ADD_LOOKUP_VALUE(string lOOKUP_SECTION, string lOOKUP_TYPE, string lOOKUP_VALUE)
        {
            var lOOKUP_SECTIONParameter = lOOKUP_SECTION != null ?
                new ObjectParameter("LOOKUP_SECTION", lOOKUP_SECTION) :
                new ObjectParameter("LOOKUP_SECTION", typeof(string));
    
            var lOOKUP_TYPEParameter = lOOKUP_TYPE != null ?
                new ObjectParameter("LOOKUP_TYPE", lOOKUP_TYPE) :
                new ObjectParameter("LOOKUP_TYPE", typeof(string));
    
            var lOOKUP_VALUEParameter = lOOKUP_VALUE != null ?
                new ObjectParameter("LOOKUP_VALUE", lOOKUP_VALUE) :
                new ObjectParameter("LOOKUP_VALUE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DOCUS_SYS_ADD_LOOKUP_VALUE", lOOKUP_SECTIONParameter, lOOKUP_TYPEParameter, lOOKUP_VALUEParameter);
        }
    
        public virtual int DOCUS_ASM_INSERT_ASSIGNMENT_NOTE(Nullable<int> aSSIGNMENT_ID, string nOTE)
        {
            var aSSIGNMENT_IDParameter = aSSIGNMENT_ID.HasValue ?
                new ObjectParameter("ASSIGNMENT_ID", aSSIGNMENT_ID) :
                new ObjectParameter("ASSIGNMENT_ID", typeof(int));
    
            var nOTEParameter = nOTE != null ?
                new ObjectParameter("NOTE", nOTE) :
                new ObjectParameter("NOTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DOCUS_ASM_INSERT_ASSIGNMENT_NOTE", aSSIGNMENT_IDParameter, nOTEParameter);
        }
    }
}
