//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_PRODLIB_CLPHDOC
    {
        public int ACCTNO { get; set; }
        public Nullable<decimal> CSTSEQ { get; set; }
        public string CUSTRF { get; set; }
        public Nullable<decimal> IMBOXC { get; set; }
        public Nullable<decimal> IMBOXU { get; set; }
    }
}
