//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_SUB_REQUEST
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date_Received { get; set; }
        public Nullable<int> GT_Loan_Number { get; set; }
        public string Borrower_Last_Name { get; set; }
        public Nullable<int> Representative_Id { get; set; }
        public Nullable<System.DateTime> Date_Assigned_To_Processor { get; set; }
        public Nullable<int> Owner_Id { get; set; }
        public string Requestor { get; set; }
        public Nullable<int> Request_Type_Id { get; set; }
        public Nullable<int> Fee_Id { get; set; }
        public Nullable<int> Request_Status_Id { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Principal_Loan_Balance { get; set; }
        public Nullable<decimal> Loan_Balance_2 { get; set; }
        public Nullable<decimal> New_Loan_Amount { get; set; }
        public Nullable<int> New_CLTV { get; set; }
        public string Comments { get; set; }
        public Nullable<int> HELOC { get; set; }
        public Nullable<int> FICO { get; set; }
        public Nullable<int> Proposed_DTI { get; set; }
        public Nullable<int> Current_DTI { get; set; }
        public Nullable<int> Loan_Type_Id { get; set; }
    }
}
