//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_SYS_CUSTODIAN
    {
        public int CUSTODIAN_ID { get; set; }
        public string CUSTODIAN_NAME { get; set; }
        public string CUSTODIAN_COMMENTS { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public System.DateTime DATE_UPDATED { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
