//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_ASM_ASSIGNMENTS
    {
        public int ASSIGNMENT_ID { get; set; }
        public Nullable<int> ACCOUNT_NUMBER { get; set; }
        public string BORROWER_LAST_NAME { get; set; }
        public Nullable<int> REQUEST_TYPE_ID { get; set; }
        public Nullable<int> REQUEST_REASON_ID { get; set; }
        public Nullable<int> DOC_TYPE_ID { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> DATE_ENTERED { get; set; }
        public Nullable<int> REQUEST_ENTERED_BY_ID { get; set; }
        public Nullable<int> REQUESTOR_NAME_ID { get; set; }
        public Nullable<bool> MERS_INDICATOR { get; set; }
        public Nullable<bool> MERS_UPDATED { get; set; }
        public string ASSIGNOR { get; set; }
        public string ASSIGNEE { get; set; }
        public Nullable<int> ASSIGNED_TO_ID { get; set; }
        public Nullable<int> PROCESSED_BY_ID { get; set; }
        public Nullable<System.DateTime> ASSIGNED_DATE { get; set; }
        public Nullable<System.DateTime> COLLATERAL_FILE_REQUEST_DATE { get; set; }
        public Nullable<bool> AOM_IN_COL { get; set; }
        public string THIRD_PARTY_CONTACT_NAME { get; set; }
        public string THIRD_PARTY_CONTACT_INFO { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public Nullable<System.DateTime> LAST_STATUS_DATE { get; set; }
        public Nullable<System.DateTime> FOLLOW_UP_DATE { get; set; }
        public Nullable<System.DateTime> SALE_DATE { get; set; }
        public Nullable<System.DateTime> DATE_COMPLETE { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string ATTENTION_TO { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<bool> RUSH { get; set; }
        public Nullable<int> CUSTODIAN_ID { get; set; }
        public string CUST_REF_NUMBER { get; set; }
        public string MERS_INFO_NUMBER { get; set; }
        public Nullable<int> LSCOD1 { get; set; }
        public Nullable<int> SBSCOD { get; set; }
        public Nullable<int> RECORDED_STATUS_ID { get; set; }
        public string RECORDED_COUNTY { get; set; }
        public Nullable<System.DateTime> RECORDED_DATE { get; set; }
        public string RECORDED_DOC_INST_NUM { get; set; }
        public string RECORDED_BOOK { get; set; }
        public string RECORDED_PAGE { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public System.DateTime DATE_UPDATED { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
