//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_PRODLIB_CLPCLMST
    {
        public decimal ACCTNO { get; set; }
        public string APPLCT { get; set; }
        public Nullable<decimal> CALIEN { get; set; }
        public Nullable<decimal> CASHDT { get; set; }
        public string CBSTAT { get; set; }
        public Nullable<decimal> CLOSCD { get; set; }
        public string COAPPL { get; set; }
        public Nullable<decimal> CONDAT { get; set; }
        public Nullable<decimal> COUNTY { get; set; }
        public Nullable<decimal> DEALER { get; set; }
        public Nullable<decimal> INTRAT { get; set; }
        public Nullable<decimal> INVNBR { get; set; }
        public Nullable<decimal> LONTYP { get; set; }
        public Nullable<decimal> LSTPAY { get; set; }
        public Nullable<decimal> MATURE { get; set; }
        public string PADDR1 { get; set; }
        public string PADDR2 { get; set; }
        public string PCITY { get; set; }
        public Nullable<decimal> POOLNO { get; set; }
        public Nullable<decimal> PRDTYP { get; set; }
        public Nullable<decimal> PRNBAL { get; set; }
        public Nullable<decimal> PROCED { get; set; }
        public string PSTATE { get; set; }
        public Nullable<decimal> PZIP { get; set; }
        public Nullable<decimal> REGION { get; set; }
        public Nullable<decimal> REGPAY { get; set; }
        public string RSTATE { get; set; }
        public Nullable<decimal> SOCSEC { get; set; }
        public Nullable<decimal> TINFIN { get; set; }
    }
}
