//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUS_ASM_ASSIGNEE
    {
        public int Assignee_Id { get; set; }
        public string Assignee_Name { get; set; }
        public bool Trustname_Required { get; set; }
        public int Sort_Order { get; set; }
    }
}
